"""组装 OpenWrt / Alpine 使用的 apk v2 包。

不依赖 SDK、abuild 或 apk-tools，只用 Python 标准库与本机 openssl：
包体是签名段 + 控制段 + 数据段的 gzip 流拼接，细节见 apk_tar 的模块说明。

用法：
  python3 scripts/apk_build.py --root <payload 目录> --out dist/wrtdeck-1.0.0-r1.apk \
      --name wrtdeck --version 1.0.0 --release 1 --arch aarch64_cortex-a53 \
      --desc "WrtDeck 轻量设备控制面板" --depend ca-bundle \
      --script post-install=packaging/apk/post-install

签名（可选）：--sign-key packaging/keys/wrtdeck-local.rsa --sign-name wrtdeck-local.rsa.pub
同时写入 .SIGN.RSA.（SHA-1）与 .SIGN.RSA256.（SHA-256）两条签名，
新老 apk-tools 都能验；公钥需放到设备的 /etc/apk/keys/ 下才被信任。
"""

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile
import time

import apk_tar

# 控制段里的安装脚本文件名，参数给出短名时补上前导点
SCRIPT_NAMES = {
    'pre-install': '.pre-install',
    'post-install': '.post-install',
    'pre-upgrade': '.pre-upgrade',
    'post-upgrade': '.post-upgrade',
    'pre-deinstall': '.pre-deinstall',
    'post-deinstall': '.post-deinstall',
    'trigger': '.trigger',
}

# 默认包描述用的项目主页
DEFAULT_URL = 'https://github.com/wrtdeck/wrtdeck'


# 构造命令行参数
def parse_args(argv):
    parser = argparse.ArgumentParser(description='组装 apk v2 包')
    parser.add_argument('--root', required=True, help='数据段根目录，目录内的文件按原路径安装')
    parser.add_argument('--out', required=True, help='输出的 .apk 路径')
    parser.add_argument('--name', required=True, help='包名')
    parser.add_argument('--version', required=True, help='版本号，如 1.0.0')
    parser.add_argument('--release', default='1', help='发布号，默认 1')
    parser.add_argument('--arch', default='aarch64_cortex-a53', help='架构名，脚本包用 noarch')
    parser.add_argument('--desc', required=True, help='一行式包描述')
    parser.add_argument('--url', default=DEFAULT_URL, help='包主页')
    parser.add_argument('--license', default='MIT', help='许可证标识')
    parser.add_argument('--maintainer', default='WrtDeck', help='维护者')
    parser.add_argument('--packager', default='WrtDeck', help='打包者')
    parser.add_argument('--depend', action='append', default=[], help='依赖，可重复')
    parser.add_argument('--provides', action='append', default=[], help='提供的能力，可重复')
    parser.add_argument('--replaces', action='append', default=[], help='替代的包，可重复')
    parser.add_argument('--script', action='append', default=[], help='安装脚本 名称=路径')
    parser.add_argument('--builddate', type=int, default=0, help='构建时间戳，0 表示取当前时间')
    parser.add_argument('--conffiles', action='append', default=[], help='需要保护的配置文件路径（仅用于自检输出）')
    parser.add_argument('--sign-key', default='', help='RSA 私钥路径，给出即签名')
    parser.add_argument('--sign-name', default='', help='公钥文件名，签名段条目名由它拼出')
    parser.add_argument('--sign-pub-out', default='', help='把公钥导出到这里，便于拷贝到设备')
    parser.add_argument('--repo', default='', help='包仓库标识，写进 origin 字段')
    return parser.parse_args(argv)


# 把 payload 目录写进数据段，权限保留可执行位，属主统一 root:root
def build_data_segment(root, mtime):
    segment = apk_tar.Segment(mtime)
    entries = []
    for parent, dirs, files in os.walk(root):
        dirs.sort()
        for name in sorted(dirs):
            full = os.path.join(parent, name)
            segment.add_dir(os.path.relpath(full, root))
        for name in sorted(files):
            full = os.path.join(parent, name)
            relative = os.path.relpath(full, root)
            if os.path.islink(full):
                segment.add_symlink(relative, os.readlink(full))
                continue
            with open(full, 'rb') as handle:
                data = handle.read()
            mode = 0o755 if os.stat(full).st_mode & 0o111 else 0o644
            # 数据段保留结束块，并且每条文件带 SHA1 校验和扩展头
            segment.add_file(relative, data, mode=mode, checksum=True)
            entries.append((relative, mode, len(data)))
    raw = apk_tar.with_trailer(segment.to_bytes())
    return apk_tar.gzip_bytes(raw), entries


# 组装 .PKGINFO，字段顺序与 abuild 保持一致，便于人工比对
def build_pkginfo(args, datahash, installed_size):
    pkgver = '%s-r%s' % (args.version, args.release)
    lines = [
        '# Generated by WrtDeck scripts/apk_build.py',
        'pkgname = %s' % args.name,
        'pkgver = %s' % pkgver,
        'pkgdesc = %s' % args.desc,
        'url = %s' % args.url,
        'builddate = %d' % (args.builddate or int(time.time())),
        'packager = %s' % args.packager,
        'size = %d' % installed_size,
        'arch = %s' % args.arch,
        'origin = %s' % (args.repo or args.name),
        'maintainer = %s' % args.maintainer,
        'license = %s' % args.license,
    ]
    for depend in args.depend:
        lines.append('depend = %s' % depend)
    # 包名与版本对 apk 而言本来就是隐含提供的。
    # 再写一行 provides = 自身名=版本 会让求解器多出一个同名同版本的「能力提供者」，
    # 与包本身互相冲突（真机上表现为 conflicts: 自己[自己=版本]），因此只写 --provides 补的额外能力。
    for provided in args.provides:
        lines.append('provides = %s' % provided)
    for replaced in args.replaces:
        lines.append('replaces = %s' % replaced)
    # datahash 是压缩后数据段的 SHA256，apk 用它校验数据段是否被替换
    lines.append('datahash = %s' % datahash)
    return ('\n'.join(lines) + '\n').encode('utf-8')


# 组装控制段：.PKGINFO 加各安装脚本
def build_control_segment(args, pkginfo, mtime):
    segment = apk_tar.Segment(mtime)
    segment.add_file('.PKGINFO', pkginfo, mode=0o644)
    for item in args.script:
        if '=' not in item:
            raise ValueError('安装脚本参数格式应为 名称=路径，实际为 %r' % item)
        name, _, path = item.partition('=')
        filename = SCRIPT_NAMES.get(name, name)
        with open(path, 'rb') as handle:
            segment.add_file(filename, handle.read(), mode=0o755)
    return apk_tar.gzip_bytes(segment.to_bytes())


# 调用 openssl 生成一段签名（DER PKCS1v15），失败即抛出
def openssl_sign(hash_name, key_path, payload_path, out_path):
    subprocess.run(
        ['openssl', 'dgst', '-' + hash_name, '-sign', key_path, '-out', out_path, payload_path],
        check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
    )


# 用私钥给控制段签名，产出签名段
def build_signature_segment(args, control_gz, mtime):
    if not args.sign_name:
        raise ValueError('签名时必须给出 --sign-name（公钥文件名）')
    if not os.path.exists(args.sign_key):
        raise ValueError('私钥不存在: %s' % args.sign_key)
    segment = apk_tar.Segment(mtime)
    with tempfile.TemporaryDirectory() as workdir:
        control_path = os.path.join(workdir, 'control.tar.gz')
        with open(control_path, 'wb') as handle:
            handle.write(control_gz)
        for prefix, hash_name in (('.SIGN.RSA.', 'sha1'), ('.SIGN.RSA256.', 'sha256')):
            signature_path = os.path.join(workdir, hash_name + '.sig')
            openssl_sign(hash_name, args.sign_key, control_path, signature_path)
            with open(signature_path, 'rb') as handle:
                signature = handle.read()
            if len(signature) < 64:
                raise ValueError('%s 签名长度异常: %d 字节' % (hash_name, len(signature)))
            segment.add_file(prefix + args.sign_name, signature, mode=0o644)
    return apk_tar.gzip_bytes(segment.to_bytes())


# 导出公钥，便于拷贝到设备的 /etc/apk/keys/
def export_public_key(key_path, out_path):
    with open(out_path, 'wb') as handle:
        subprocess.run(['openssl', 'rsa', '-in', key_path, '-pubout'],
                       check=True, stdout=handle, stderr=subprocess.PIPE)


# 回读刚写出的包，确认段数、段类型与签名都在位
def verify_package(path, expect_signature):
    with open(path, 'rb') as handle:
        data = handle.read()
    members = apk_tar.split_members(data)
    expected = 3 if expect_signature else 2
    if len(members) != expected:
        raise ValueError('段数应为 %d，实际 %d' % (expected, len(members)))
    control_entries = apk_tar.read_entries(members[-2])
    names = [entry['name'] for entry in control_entries]
    if '.PKGINFO' not in names:
        raise ValueError('控制段里没有 .PKGINFO')
    if expect_signature:
        signatures = [entry['name'] for entry in apk_tar.read_entries(members[0])]
        if len(signatures) != 2:
            raise ValueError('签名段里应有两条签名，实际 %r' % signatures)
    fields = apk_tar.pkginfo_fields(control_entries)
    if not fields.get('pkgver'):
        raise ValueError('.PKGINFO 缺少 pkgver')
    return members, fields


# 主流程
def main(argv):
    args = parse_args(argv)
    mtime = args.builddate or int(time.time())
    if args.sign_key and not os.path.exists(args.sign_key):
        raise SystemExit('私钥不存在: %s' % args.sign_key)

    data_gz, entries = build_data_segment(args.root, mtime)
    installed_size = sum(item[2] for item in entries)
    datahash = hashlib.sha256(data_gz).hexdigest()
    pkginfo = build_pkginfo(args, datahash, installed_size)
    control_gz = build_control_segment(args, pkginfo, mtime)
    prefix = b''
    if args.sign_key:
        prefix = build_signature_segment(args, control_gz, mtime)

    out_dir = os.path.dirname(os.path.abspath(args.out))
    os.makedirs(out_dir, exist_ok=True)
    with open(args.out, 'wb') as handle:
        handle.write(prefix + control_gz + data_gz)

    if args.sign_key and args.sign_pub_out:
        os.makedirs(os.path.dirname(os.path.abspath(args.sign_pub_out)), exist_ok=True)
        export_public_key(args.sign_key, args.sign_pub_out)

    members, fields = verify_package(args.out, bool(args.sign_key))
    size = os.path.getsize(args.out)
    print('[apk] 包名 %s  版本 %s' % (fields['pkgname'][0], fields['pkgver'][0]))
    print('[apk] 架构 %s  段数 %d  文件 %d 个  安装占用 %d 字节' % (
        fields['arch'][0], len(members), len(entries), installed_size))
    if args.conffiles:
        print('[apk] 声明保护配置 %s' % ' '.join(args.conffiles))
    print('[apk] 产物 %s  %d 字节' % (args.out, size))
    if args.sign_key:
        print('[apk] 已签名，公钥 %s 需放到设备 /etc/apk/keys/' % args.sign_name)
    else:
        print('[apk] 未签名，安装时需 apk add --allow-untrusted')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
